### ISSUE TITLE
How can I make a day of the week a non-business day?

### ISSUE THREAD

**Issue by beard7** [kylekatarnls/business-day#106]
Forgive me if this is a dumb question, but is there a simple way to make a day of the week a non-business day?

I'd like the option of configuring additional weekdays as non-business, i.e every Tuesday and Thursday, for example.

Am I barking up the wrong tree trying to do this with this mixin?

**Comment by kylekatarnls** [comment]
Hello, [business-time](https://github.com/kylekatarnls/business-time) can handle that. It allow you to have holidays like in business-day, plus a schedule of open/closed hours for the week. Those hours an be `00:00-24:00` so the whole day.
