### ISSUE TITLE
Prayer day is no longer a holiday in Denmark

### ISSUE THREAD

**Issue by FlexBoom** [kylekatarnls/business-day#118]
Please remove [Prayer day](https://github.com/kylekatarnls/business-day/blob/a623e6d281c11f89a3b721cdfac3575b11e41497/src/Cmixin/Holidays/dk-national.php#L10) from `dk-national`.

Sources:
- https://da.wikipedia.org/wiki/Store_bededag#Afskaffelsen_i_2023
- https://www.nytimes.com/2023/03/01/world/europe/denmark-great-prayer-day-military-nato.html

**Comment by kylekatarnls** [comment]
Fixed in [version 1.18.0](https://github.com/kylekatarnls/business-day/releases/tag/1.18.0)
