### ISSUE TITLE
Carbon 3: Method diffInBusinessdays does not exist 

### ISSUE THREAD

**Issue by ekrist1** [kylekatarnls/business-day#120]
I got this error on both my Laravel 11 app, and the Sandbox environment produce the same error: Method diffInBusinessdays does not exist

It's working if you are using Carbon v2 in the Sandbox environment, but the latest Carbon 3 version fails when calling this method.

<img width="1344" alt="Screenshot 2024-04-02 at 22 16 55" src="https://github.com/kylekatarnls/business-day/assets/8544305/0986ab08-431d-459b-9dda-0167572294c4">

**Comment by kylekatarnls** [comment]
That's surprising 🤔 

If I do the same locally I get the result. Also all the tests are passing with Carbon 3 in the GitHub Actions. I will try to figure out what's different in the sandbox.

**Comment by kylekatarnls** [comment]
I found the problem it's a regression in Carbon 3.2.0.

**Comment by kylekatarnls** [comment]
Fixed in Carbon 3.2.4.
