### ISSUE TITLE
Location Names 

### ISSUE THREAD

**Issue by SoftCreatR** [kylekatarnls/business-day#130]
While the names of most holiday files are straightforward, there are several that lack clear context, making it difficult to understand their purpose at a glance. For example:

ad-07.php

ag-10.php

at-1.php

hr-17.php

These files are not immediately intuitive, as they only contain short codes or numbers that don’t provide sufficient information about the region, country, or specific holiday they represent. Without additional context, it's challenging for users to understand what each file refers to without opening and inspecting its contents manually.

It would be beneficial if these files included at least a brief comment or annotation, specifying the location, region, or the holiday they correspond to. For instance, a comment at the top of each file could indicate the country or holiday name associated with the file, making it much more user-friendly.

An even better improvement would be to introduce a method or utility that programmatically lists all available holiday files, alongside their respective names or titles. This could serve as a directory of holidays, giving developers a clear and comprehensive overview of all available options without having to dig through individual files. 

In my case, for example, I am looking to provide a drop-down menu for my users, allowing them to easily select their preferred holiday set. Currently, I am only able to offer a list of file names, which are often cryptic or unclear, leaving the user to guess which holiday set corresponds to their region or preferences. This is far from ideal, as it leads to confusion and a poor user experience.

Without clear descriptions or labels, users are left trying to decipher file names such as "ad-07.php" or "ag-10.php," which provide no immediate indication of the holiday set's location or significance. This creates unnecessary friction in the user interface, especially for those who are unfamiliar with the codes or abbreviations used.

Imho, an ideal solution would be the implementation of a method or API that automatically generates a comprehensive list of all available holiday sets, complete with human-readable names or descriptions. This could allow developers like me to populate a drop-down menu with clear and understandable options, such as "Andorra - National Holidays" or "Austria - Regional Holidays," instead of just ambiguous file names.

**Comment by SoftCreatR** [comment]
I just discovered that there is already a method called getHolidaysAvailableRegions, which returns a list of the available region files. This is a great starting point, but it currently only provides a list of file names, which are often too cryptic or unclear for users to understand. While the method serves its basic purpose, it falls short of offering a complete solution in terms of usability.

**Comment by kylekatarnls** [comment]
Hello the naming follows [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) and you can get the country name from it in different languages using another package such as [symfony/intl](https://symfony.com/doc/current/components/intl.html).

Then the suffix is "national" if it's the default for this given country. Other suffixes are subdivisions that are typically well known by people living there. Your first example with ad-07, AD is Andorra ISO code, and 07 stands for the seventh parish [Escaldes-Engordany](https://fr.wikipedia.org/wiki/Escaldes-Engordany). For US (United States), the suffix is the 2-letter code for the state commonly used there.

I am reluctant to embed such package in this library. I would prefer to keep it small and serve only one purpose. And as it uses an ISO norm, it's straightforward to delegate it to another PHP library or a front-end one.

On another side, I'm open to pull-requests to introduce names for the suffixes. To be noted: English might not work for everyone on this matter (such as AT-3 would be known as "Niederösterreich" locally but referred as "Lower Austria" in English).

**Comment by SoftCreatR** [comment]
Thank you for your help. Although I wasn't able to find an easy method to translate all the region codes accurately, I did manage to come up with a workaround that suits my needs for now. While it may not be the most straightforward solution, it gets the job done for my current requirements.
