### ISSUE TITLE
'2024-10-17', '2024-10-18', '2024-10-21', '2024-10-22' wrongly marked as holiday for sg-national yet sg-national.php doesnt have them

### ISSUE THREAD

**Issue by ziming** [kylekatarnls/business-day#132]
Not sure why but 

'2024-10-17',
'2024-10-18',
'2024-10-21',
'2024-10-22',

are marked as holidays when I check if it's holiday on those dates. my region is set to sg-national. When I use getHolidayName(), 18 gives back Deepavali & 17, 21, 22 gives back "Unknown"

These dates are not holidays in sg-national calendar this year (2024)

But when i check the code in this file I don't see those dates, so very weird

https://github.com/kylekatarnls/business-day/blob/master/src/Cmixin/Holidays/sg-national.php

**Comment by kylekatarnls** [comment]
Indeed it's a bug.

`Carbon::parse('2024-10-17')->getHolidayId()` returns `2028-10-17` so the year-filter is misbehaving.

**Comment by kylekatarnls** [comment]
The issue as been fixed in 1.18.6.
