### ISSUE TITLE
Other result after upgrade from 1.2.0 to 1.3.0

### ISSUE THREAD

**Issue by mnabialek** [kylekatarnls/business-day#25]
I have the following code (in Laravel app):

```
        BusinessDay::enable(\Illuminate\Support\Carbon::class);
        Carbon::setHolidaysRegion('fr-national');
        dd(Carbon::parse('2018-01-06 12:00:00')->isHoliday());
```

In version 1.2.0 result of this is `true`. However after upgrade to 1.3.0 result is `false`. Is there anything that should be changed to use version 1.3 or maybe this is a bug?

**Comment by kylekatarnls** [comment]
Hi,

It's a bug fix, I'm French, and I can confirm January the 6th is not an holiday.

**Comment by kylekatarnls** [comment]
From 1.3.0, holidays files are a lot easier to read:
[src/Cmixin/Holidays/fr-national.php](https://github.com/kylekatarnls/business-day/blob/master/src/Cmixin/Holidays/fr-national.php)

See all the available files:
[src/Cmixin/Holidays](https://github.com/kylekatarnls/business-day/blob/master/src/Cmixin/Holidays/)

And you can compare to:
https://www.timeanddate.com/holidays/france/2018

The lists of **National holiday** dates of timeanddate.com are correct.

If you see any incoherence between our files and the actual dates, please let me know.

**Comment by mnabialek** [comment]
Ok, thanks for info. Previously there was `'06/01', // Épiphanie` but now it's removed so it seems to be fine.
