### ISSUE TITLE
Holiday Date format inconsistency

### ISSUE THREAD

**Issue by mikemand** [kylekatarnls/business-day#27]
Hi Kyle,

The new changes are really awesome, congrats on being able to handle so many different and complex holidays.

The docs are a little inconsistent now. In some places, you are using `m-d` and in others, you are using `d/m`. Does it matter which syntax we use?

Some examples:

[`m-d`](https://github.com/kylekatarnls/business-day#usage)
```php
'boss-birthday'    => '09-26', // Close the office on September 26th
```

[`d/m`](https://github.com/kylekatarnls/business-day#setholidays)
```php
Carbon::setHolidays('my-enterprise', array(
    'lincolns-birthday' => array(
        'date'     => '12/02',
        'observed' => true,
        'name'     => array(
            'en' => "Lincoln's Birthday",
            'fr' => 'Anniversaire du Président Lincoln',
        ),
    ),
));
```

[`d/m`](https://github.com/kylekatarnls/business-day#addholidays)
```php
Carbon::addHolidays('my-list', array(
    'poney'        => '20/01',
    'swimmingpool' => '21/01',
)));
Carbon::addHolidays('my-list', array(
    'boss-birthday'          => '10/02',
    'boss-birthday-next-day' => '11/02',
)));
Carbon::getHolidays('my-list') // contains 20/01, 21/01, 10/02 and 11/02
```

**Comment by kylekatarnls** [comment]
We now support both `-` if you prefer the month first, `/` if you prefer the day first.

`m-d` is internally converted to `d/m` so using directly `d/m` is a bit faster to parse. If you don't mind, use `d/m` for performance.

I will add it in the README.
