### ISSUE TITLE
[Feature Request] List of all holidays for year

### ISSUE THREAD

**Issue by mikemand** [kylekatarnls/business-day#28]
Hi Kyle,

If I missed a function for this already, please let me know. I checked each class, but besides `Carbon::getHolidays();` (more on that below), I didn't see anything that looked like it would do what I want.

I would like to get a list of all holidays for a specified year (defaulting to this year if nothing was passed). `Carbon::getHolidays();` is close, but I would like an array keyed by the holiday's name (translated based on Carbon's current locale) and all closure holidays already computed.

I'm making a page [similar to this](https://www.umb.com/personal/aboutumb/company/holiday-schedule/) for my client, and since we're already setting the holidays in Carbon, I would like to just pull that out.

**Comment by kylekatarnls** [comment]
It exists but not yet documented, it's `getYearHolidays`:

```php
Carbon::getYearHolidays(); // list of holidays for current year
Carbon::getYearHolidays(2020); // list of holidays for year 2020
```

Here is the method:
https://github.com/kylekatarnls/business-day/blob/2dc8e19b6072fa325767066a10b231b0c60c400e/src/Cmixin/BusinessDay/YearCrawler.php#L12

It was used internally only in my mind but it could be used as a public method safely.

I will add an example for this usage in the README.

**Comment by kylekatarnls** [comment]
It's now documented: https://github.com/kylekatarnls/business-day#getyearholidays

**Comment by mikemand** [comment]
Awesome Kyle, thank you.
