### ISSUE TITLE
Easter Monday in AU-WA not recognised

### ISSUE THREAD

**Issue by njbarrett** [kylekatarnls/business-day#33]
Hello,
Just recently we observed Easter Monday as a public holiday in `au-wa` on the 22nd April 2019

However after seeing an inconsistency in a report we noticed that this day was not recognised as a holiday by the package. I've been able to manually add it since, but do you have any ideas why it wasn't picked up?

Thanks

**Comment by kylekatarnls** [comment]
I see why, `'easter-1'` key has been used for both Easter +1 day and Easter -1 day, and Easter Saturday day erased Easter Monday.

I will just change the key and it will be fixed.

**Comment by njbarrett** [comment]
Amazing work, thank you
