### ISSUE TITLE
slow diffInBusinessDays()

### ISSUE THREAD

**Issue by bzoks** [kylekatarnls/business-day#34]
I need to calculate diffs between many dates and found out that diffInBusinessDays() is very slow.
Could this be somehow improved?
The larger is difference between two dates, the slower it gets.

As an example: for calculating diff in business days between today and every day for next year, it takes approx 30 seconds (not microseconds) - and that is for 365 calls.
Sample code:
```php
<?php
require_once ("../vendor/autoload.php");

use Carbon\Carbon;
use Cmixin\BusinessDay;

function test()
{
    BusinessDay::enable(Carbon::class);
    Carbon::setHolidaysRegion('si-national');
    $time_start = microtime(true);
    $dt1 = Carbon::today();
    for ($i = 1; $i <= 365; $i++) {
        $dt2 = Carbon::today();
        $dt2->addDays($i);
        $diff = $dt1->diffInBusinessDays($dt2);
        print "diff in business days: " . $diff . PHP_EOL;
    }
    $time_end = microtime(true);
    $duration = $time_end - $time_start;
    print "elapsed: " . $duration . " s" . PHP_EOL;
}
test();
```    

Using cmixin/business-day 1.6.0 with PHP 7.2.14,... 

Best regards,
  Bostjan

**Comment by kylekatarnls** [comment]
Hello,

> As an example: for calculating diff in business days between today and every day for next year, it takes approx 30 seconds (not microseconds) - and that is for 365 calls.

Sorry, but it's not designed for such usages. `diffInBusinessDays` will iterate on each day to check if it's `isBusinessDay` (not weekend nor holiday).

But you just have to check only once each day, cache the result to reuse it and then you get less than 300ms:

```php
function test()
{
    BusinessDay::enable(Carbon::class);
    Carbon::setHolidaysRegion('si-national');
    $time_start = microtime(true);
    $count = 0;
    for ($i = 1; $i <= 365; $i++) {
        $dt2 = Carbon::today();
        $dt2->addDays($i);
        if ($dt2->isBusinessDay()) {
            $count++;
        }
        print "diff in business days: " . $count . PHP_EOL;
    }
    $time_end = microtime(true);
    $duration = $time_end - $time_start;
    print "elapsed: " . $duration . " s" . PHP_EOL;
}
```

**Comment by bzoks** [comment]
This example was just for testing purposes, my real use case is that I must calculate diff for few 100 dates of which only some might overlap, and they will be distributed over next few months. Number of dates will grow, so this function will have even bigger impact on speed.

**Comment by kylekatarnls** [comment]
I did not say, you must run this function every time. I said, you must run **once** this function and reuse its result (stored in a cache). It's like writing once for all you calendar and for each day if it's or not a business day or not, then when you want a diff, come pick the count from it.

Our library is not responsible for business caching logic. But here is a simple example:

```php
$cache = __DIR__.'/cache-directory/si-national-calendar.json';
$calendar = file_exists($cache) ? json_encode(file_get_contents($cache), JSON_OBJECT_AS_ARRAY);
$touched = false;

$diff = $date1->diffInDaysFiltered(function(Carbon $date) use (&$calendar, &$touched) {
  $key = $date->format('Y-m-d');

  if (!isset($calendar[$key])) {
    $calendar[$key] = $date->isBusinessDay();
    $touched = true;
  }

 return $calendar[$key];
}, $date2);

if ($touched) {
  file_put_contents($cache, json_encode($calendar));
}

var_dump($diff);
```

This will write in a cache if you meet a day you did not check before, else it reuses the previous result. Then you can cleanup values in the past times to times if you don't need them.

**Comment by bzoks** [comment]
Ok, thanks for great idea.
