### ISSUE TITLE
Usage with Laravel

### ISSUE THREAD

**Issue by AdrienPoupa** [kylekatarnls/business-day#38]
Hi,

Great library, thanks!

I am trying to use it with Laravel and the instructions are a bit confusing.

I created the carbon.php config file as instructed in the readme, but this alone is not enough to enable it in Laravel.

I also added the following to my composer.json file as shown in #29 with no luck

```
  "extra": {
    "laravel": {
      "providers": [
        "Cmixin\\BusinessDay\\BusinessDayServiceProvider"
      ]
    }
  }
```

same with

```
  "extra": {
    "laravel": {
      "providers": [
        "Cmixin\\BusinessDay\\Laravel\\ServiceProvider"
      ]
    }
  }
```

The only thing that worked was to manually add the ServiceProvider in the providers section of app.php:

`\Cmixin\BusinessDay\Laravel\ServiceProvider::class,`

Is it the expected behavior?

**Comment by kylekatarnls** [comment]
I guess you're using Laravel 6. I realize this library is not compatible with the new version.

**Comment by kylekatarnls** [comment]
Note than you can remove the extra.laravel setting from your composer.json, you're not supposed to need it.

**Comment by kylekatarnls** [comment]
Hi can you retry using version 1.7.0?

```
composer require cmixin/business-day:^1.5
```

**Comment by AdrienPoupa** [comment]
It's working, thanks!

```
  - Updating cmixin/business-day (1.6.2 => 1.7.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: cmixin/business-day
```
