### ISSUE TITLE
Drop PHP-5.x version supports

### ISSUE THREAD

**Issue by peter279k** [kylekatarnls/business-day#39]
As title, it seems that the `php-5.x` version have been inactive for about years.

I think it's time to drop them.

@kylekatarnls, what do you think about this :)?

**Comment by kylekatarnls** [comment]
Yes, it's fine to drop it. Minimum version could be 7.1.8 as it is the minimum version of Carbon 2 (and we could also drop Carbon 1 in a next step or in the same time). Dropping PHP 5 implies to replace every syntaxes that evolved to reflect the standard of PHP 7: `array()` => `[]` for instance, typing, `??` operator, etc.

**Comment by kylekatarnls** [comment]
Of course, this can be done step by step with

**Comment by peter279k** [comment]
I've created PR to resolve this issue.

If having any problem, please feel free to write comments on this PR :).
