### ISSUE TITLE
Laravel Vapor Integration 

### ISSUE THREAD

**Issue by DavidLambauer** [kylekatarnls/business-day#42]
Hi, recently we switched to Laravel Vapor. We're using your lib within a CLI command which we can trigger manually on Laravel Vapor. Unfortunately, the following error is thrown:

```
Symfony\Component\Debug\Exception\FatalThrowableError
4:59:06 PM
Call to undefined function Cmixin\BusinessDay\easter_days()
/var/task/vendor/cmixin/business-day/src/Cmixin/BusinessDay/HolidayCalculator.php:92
```

I am not able to reproduce it locally. Within the CLI Command, we enable the business day plugin like so:

```php
BusinessDay::enable(Carbon::class, $this->option('holiday-list'));
```

`$this->option('holiday-list')` refers to `de-hh`. Later in the process, we trigger `::isHoliday()`. 

As I said, I am not able to reproduce it locally. Is this something related to the whole serverless thing? Any ideas? Every help would be great.

**Comment by kylekatarnls** [comment]
Hi,

As specified in the composer.json, business-day requires ext-calendar:
https://github.com/kylekatarnls/business-day/blob/master/composer.json#L8

Which is the extension that contains this method:
https://www.php.net/manual/en/function.easter-days.php

composer should throw an exception during the install/update if this extension is not enabled in the current running php version.

This seems to be a Vapor issue considering this open issue: https://github.com/laravel/vapor-php-build/issues/3

I guess it's not yet possible to enable/disable PHP extensions.

You can probably install a polyfill for this function, so it could work without the extension.

Check https://github.com/jdecool/polyfill-easter or https://packagist.org/packages/fisharebest/ext-calendar
