### ISSUE TITLE
Type hinting bug in previousBusinessDay

### ISSUE THREAD

**Issue by larsrbak** [kylekatarnls/business-day#48]
Bug in initiated and static types. Specifically the method `previousBusinessDay`. Code hinting suggests that the methods returns a boolean. I've tested it and found it returned a carbon instance (as expected).

version  1.7.2

**Comment by kylekatarnls** [comment]
Indeed, the type is incorrect this method and current/next:
https://github.com/kylekatarnls/business-day/blob/0f80187f3ce551de1247d2bb1840bfcedf92995d/src/Cmixin/BusinessDay/BusinessCalendar.php#L96

**Comment by kylekatarnls** [comment]
Fix released. Thanks.
