### ISSUE TITLE
MixinBase contains non-macro methods

### ISSUE THREAD

**Issue by hackel** [kylekatarnls/business-day#49]
Currently, `\Cmixin\BusinessDay\MixinBase::getCarbonClass` and `\Cmixin\BusinessDay\MixinBase::enable` are both being added as Carbon macros.  The latter seems to account for this at least, but does nothing.  The former doesn't even return a callback, so just breaks:
```php
\Carbon\Carbon::getCarbonClass()
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'Illuminate/Support/Carbon' not found or invalid function name in vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2299
```

The error arose because I tried to use [tutorigo/laravel-ide-macros](https://github.com/KristofMorva/laravel-ide-macros) which scans all registered Carbon macros in order to produce an IDE helper file.  When it got to `getCarbonClass`, it blew up.  Since it's deprecated, I'm assuming it only exists for some backward compatibility issue? 

It also looks like the entire `enable` method could simply be moved into the service provider to avoid registering it as a pointless macro if you just make `$carbonClass` public.  It's still not clear to me what the point of setting it is, so I'm probably missing something.

**Comment by kylekatarnls** [comment]
For the record, business-day comes with its own helper files out of the box, so you can exclude it from laravel-ide-macros.

Here is the easy fix:
```php
Carbon::macro('getCarbonClass', function () {
  return self::class;
});
```

This issue with `getCarbonClass` is one of the reason for deprecation. I'll get rid of it in the next major version.

**Comment by kylekatarnls** [comment]
Regarding the low probability for this method to actually used in applications, I will drop it and release 1.8.0.
