### ISSUE TITLE
Add week-end exceptions

### ISSUE THREAD

**Issue by ha3jo** [kylekatarnls/business-day#54]
So in our country there are some saturdays that are business day, every year goverment decide wich saturdays are business days.
This is because if between a holiday and weekend is only 1 business day, they swap it with next saturday. 

in code i've inserted for example the following:

```
 public function isBusinessDay()
    {
        $mixin = $this;

        /**
         * Checks the date to see if it is a business day (neither a weekend day nor a holiday).
         *
         * @return bool
         */
        return function ($self = null) use ($mixin) {
            $carbonClass = @get_class() ?: Emulator::getClass(new \Exception());

            /** @var \Carbon\Carbon|\Cmixin\BusinessDay $self */

            $self = $carbonClass::getThisOrToday($self, isset($this) && $this !== $mixin ? $this : null);
            //exception by hand need to automate
            if ($self->format('Y-m-d') == '2020-12-12') {$except = true;} else {$except = false; }

            return ($self->isWeekday() or $except) && !$self->isHoliday();
        };
    }
```

I would more elegant to have a list in an array

Joe

**Comment by ha3jo** [comment]
for multiple date exceptions:

```
   public function isBusinessDay()
    {
        $mixin = $this;

        /**
         * Checks the date to see if it is a business day (neither a weekend day nor a holiday).
         *
         * @return bool
         */
        return function ($self = null) use ($mixin) {
            $carbonClass = @get_class() ?: Emulator::getClass(new \Exception());

            /** @var \Carbon\Carbon|\Cmixin\BusinessDay $self */

            $self = $carbonClass::getThisOrToday($self, isset($this) && $this !== $mixin ? $this : null);
            //exception by hand need to automate
            //array of dates
            $ex=array('2020-12-12','2021-12-11');
            if (in_array( $self->format('Y-m-d'), $ex)) {$except = true;} else {$except = false; }
    

            return ($self->isWeekday() or $except) && !$self->isHoliday();
        };
    }
```

**Comment by ha3jo** [comment]
Resolved!

define the extradays in config/global.php
```

return [

    'extraworkdays' => ['2020-12-12', '2021-12-11'],
]

?>
```
And in BussinessCalendar.php 

```
   public function isBusinessDay()
    {
        $mixin = $this;

        /**
         * Checks the date to see if it is a business day (neither a weekend day nor a holiday).
         *
         * @return bool
         */
        return function ($self = null) use ($mixin) {
            $carbonClass = @get_class() ?: Emulator::getClass(new \Exception());

            /** @var \Carbon\Carbon|\Cmixin\BusinessDay $self */

            $self = $carbonClass::getThisOrToday($self, isset($this) && $this !== $mixin ? $this : null);
            //array of dates put in config global.php 
            $ex = config('global.extraworkdays');
            if (in_array( $self->format('Y-m-d'), $ex)) {$except = true;} else {$except = false; }
    

            return ($self->isWeekday() or $except) && !$self->isHoliday();
        };
    }
```

that's all.

**Comment by kylekatarnls** [comment]
If you modify code on vendor, you'll lose it next time someone will run `composer update`, and/or on deploy. Why not just add holidays the normal way following the documentation example?
https://github.com/kylekatarnls/business-day#setholidays

**Comment by ha3jo** [comment]
> Why not just add holidays the normal way following the documentation example?
> https://github.com/kylekatarnls/business-day#setholidays
i couldnt find here method for setting a saturday as business day...

**Comment by kylekatarnls** [comment]
Yes I first believed you were cancelling holidays which is possible, but the `isWeekday` is based on `$weekendDays` in `Carbon` class which is fixed for every week. So short answer:

With the current version of business-day, you can't do that.

You have to add exception in you application code (not the vendor directory code), you should consider the vendor directory as read-only. Else you'll get so many trouble when deploying your app in different environments, working with teams, updating dependencies...

But a really correct way to handle it is implement an option in business-day library so it can call a custom method instead of `isWeekday()` and then you would be able to customize what is a weekday in your business using a closure.

**Comment by ha3jo** [comment]
Thanks for reply!

Ok, i will put a pull-request here, my little modification could be implemented anyway?

**Comment by kylekatarnls** [comment]
No sorry, actually it can't, business-day works well in any framework or PHP application but `config()` is a Laravel function. If you add this for every business-day, you'll break the app of every users having business-day running on non-Laravel applications.

**Comment by kylekatarnls** [comment]
Follow-up in #55.
