### ISSUE TITLE
weekend day as business day feature add

### ISSUE THREAD

**Issue by ha3jo** [kylekatarnls/business-day#55]
There is situation when is nedeed to add a weekend day as business day. 

a possible way is to modify BusinessCalendar.php

```php
   public function isBusinessDay()
    {
        $mixin = $this;

        /**
         * Checks the date to see if it is a business day (neither a weekend day nor a holiday).
         *
         * @return bool
         */
        return function ($self = null) use ($mixin) {
            $carbonClass = @get_class() ?: Emulator::getClass(new \Exception());

            /** @var \Carbon\Carbon|\Cmixin\BusinessDay $self */

            $self = $carbonClass::getThisOrToday($self, isset($this) && $this !== $mixin ? $this : null);
            //array of dates put in config global.php 
            $except = in_array($self->format('Y-m-d'), config('global.extraworkdays'));

            return ($self->isWeekday() or $except) && !$self->isHoliday();
        };
    }
```
the array of extraworkdays could be defined in config/carbon.php also, i think
any other suggestions? purposes?

**Comment by kylekatarnls** [comment]
business-day only requirement is `Carbon` which does not include the `config()` function. I guess you took it from Laravel helpers.

The solution has to be Laravel-free to not break the applications for all the users having business-day running on non-Laravel applications.

**Comment by ha3jo** [comment]
the array of extraworkdays could be defined incmixin/business-day/src/Cmixin/  to work in any application

**Comment by kylekatarnls** [comment]
With the version 1.10.0, you can now do it properly without breaking your vendor directory using [setBusinessDayChecker()](https://github.com/kylekatarnls/business-day#setbusinessdaychecker):

```php
Carbon::setBusinessDayChecker(function (CarbonInterface $date) {
    return $date->isWeekday()
        && !$date->isHoliday()
        || in_array($date->format('Y-m-d'), config('global.extraworkdays'));
});
```

If you're using Laravel, this can go in the AppService boot method:
https://github.com/laravel/laravel/blob/v8.4.4/app/Providers/AppServiceProvider.php#L24

Thanks.
