### ISSUE TITLE
Warning:  Cannot bind an instance to a static closure in vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2413

### ISSUE THREAD

**Issue by mpoma** [kylekatarnls/business-day#64]
Hello.
I have a lot of <warning>PHP Warning:  Cannot bind an instance to a static closure in /home/mapi/Development/rapsnova/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2413</warning>
in tinker did now()->isHoliday() and I get the warnings

**Comment by kylekatarnls** [comment]
Please provide your config (the code with `BusinessDay::enable(...`) and your Carbon version so I can try to reproduce.

**Comment by mpoma** [comment]
mi carbon.php is a customized file,with not standart region,  laravel 8.25,    "nesbot/carbon", "version": "2.44.0",

<?php 

return [
    'holidays' => [
        'region' => 'raps-national',
        'with' => [
            'new-year'                                                  => '01-01',
            'easter-48'                                                 => '= easter -48',
            'easter-47'                                                 => '= easter -47',
            'day-of-remembrance-for-truth-and-justice'                  => '03-24',
            'bridge-day'                                                => '= 03-24 if Tuesday then previous Monday and if Thursday then next Friday',
            'saint-thursday'                                            => '= easter -3',
            'saint-friday'                                              => '= easter -2',
            'day-of-the-veterans-and-the-fallen-of-malvinas-war'        => '04-02',
            'substitutes-day-of-the-veterans'                           => '= 04-02 if Tuesday then previous Monday and if Thursday then next Friday',
            'labor-day'                                                 => '05-01',
            'substitutes-labor-day'                                     => '= 05-01 if Tuesday then previous Monday and if Thursday then next Friday',
            'day-of-the-first-national-government'                      => '05-25',
            'substitutes-may-revolution'                                => '= 05-25 if Tuesday then previous Monday and if Thursday then next Friday',
            'guemes-day'                                                => '= 06-17 if Tuesday then previous Monday and if Wednesday,Thursday,Friday,Saturday,Sunday then next Monday',
            'national-flag-day'                                         => '06-20',
            'substitutes-flag-day'                                      => '= 06-20 if Tuesday then previous Monday and if Thursday then next Friday',
            'independence-day'                                          => '07-09',
            'anniversary-of-the-death-of-general-josyo-de-san-martyun'  => '= 08-17 if Tuesday then previous Monday and if Thursday then next Monday',
            'day-of-respect-for-cultural-diversity'                     => '= 10-12 if Tuesday,Wednesday then previous Monday and if Thursday,Friday,Saturday,Sunday then next Monday',
            'substitutes-day-of-respect-for-cultural-diversity'         => '10-08',
            'day-of-national-sovereignty'                               => '11-20',
            'substitutes-soberany-day'                                  => '= 11-20 if Tuesday,Wednesday then previous Monday and if Thursday,Friday,Saturday,Sunday then next Monday',
            'virgin-day'                                                => '12-08',
            'substitutes-virgin-day'                                    => '= 12-08 if Tuesday then previous Monday and if Thursday then next Friday',
            'noche-buena'                                               => '12-24',
            'christmas'                                                 => '12-25',
            'substitutes-christmas'                                     => '= 12-25 if Tuesday then previous Monday and if Thursday then next Friday',
            'noche-vieja'                                               => '12-31',
        ],
        // extra work days (even if in the weekend)
        'without' => [],
    ],
];

**Comment by kylekatarnls** [comment]
I tried your settings but couldn't reproduce the error:
https://try-carbon.herokuapp.com/?embed&input=%24settings%20%3D%20%20%5B%0D%0A%20%20%20%20%27holidays%27%20%3D%3E%20%5B%0D%0A%20%20%20%20%20%20%20%20%27region%27%20%3D%3E%20%27raps-national%27%2C%0D%0A%20%20%20%20%20%20%20%20%27with%27%20%3D%3E%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27new-year%27%20%20%3D%3E%20%2701-01%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27easter-48%27%20%20%3D%3E%20%27%3D%20easter%20-48%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27easter-47%27%20%20%3D%3E%20%27%3D%20easter%20-47%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27day-of-remembrance-for-truth-and-justice%27%20%20%20%3D%3E%20%2703-24%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27bridge-day%27%20%20%3D%3E%20%27%3D%2003-24%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27saint-thursday%27%20%20%20%20%3D%3E%20%27%3D%20easter%20-3%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27saint-friday%27%20%20%3D%3E%20%27%3D%20easter%20-2%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27day-of-the-veterans-and-the-fallen-of-malvinas-war%27%20%20%20%20%20%20%20%20%3D%3E%20%2704-02%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-day-of-the-veterans%27%20%20%3D%3E%20%27%3D%2004-02%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27labor-day%27%20%3D%3E%20%2705-01%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-labor-day%27%20%3D%3E%20%27%3D%2005-01%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27day-of-the-first-national-government%27%20%20%20%3D%3E%20%2705-25%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-may-revolution%27%20%20%3D%3E%20%27%3D%2005-25%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27guemes-day%27%20%20%20%3D%3E%20%27%3D%2006-17%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Wednesday%2CThursday%2CFriday%2CSaturday%2CSunday%20then%20next%20Monday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27national-flag-day%27%20%3D%3E%20%2706-20%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-flag-day%27%20%3D%3E%20%27%3D%2006-20%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27independence-day%27%20%20%3D%3E%20%2707-09%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27anniversary-of-the-death-of-general-josyo-de-san-martyun%27%20%20%3D%3E%20%27%3D%2008-17%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Monday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27day-of-respect-for-cultural-diversity%27%20%20%20%3D%3E%20%27%3D%2010-12%20if%20Tuesday%2CWednesday%20then%20previous%20Monday%20and%20if%20Thursday%2CFriday%2CSaturday%2CSunday%20then%20next%20Monday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-day-of-respect-for-cultural-diversity%27%3D%3E%20%2710-08%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27day-of-national-sovereignty%27%20%20%3D%3E%20%2711-20%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-soberany-day%27%20%20%20%3D%3E%20%27%3D%2011-20%20if%20Tuesday%2CWednesday%20then%20previous%20Monday%20and%20if%20Thursday%2CFriday%2CSaturday%2CSunday%20then%20next%20Monday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27virgin-day%27%20%3D%3E%20%2712-08%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-virgin-day%27%20%20%20%3D%3E%20%27%3D%2012-08%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27noche-buena%27%20%20%20%3D%3E%20%2712-24%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27christmas%27%20%20%20%3D%3E%20%2712-25%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27substitutes-christmas%27%20%20%20%3D%3E%20%27%3D%2012-25%20if%20Tuesday%20then%20previous%20Monday%20and%20if%20Thursday%20then%20next%20Friday%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%27noche-vieja%27%20%20%3D%3E%20%2712-31%27%2C%0D%0A%20%20%20%20%20%20%20%20%5D%2C%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20extra%20work%20days%20(even%20if%20in%20the%20weekend)%0D%0A%20%20%20%20%20%20%20%20%27without%27%20%3D%3E%20%5B%5D%2C%0D%0A%20%20%20%20%5D%2C%0D%0A%5D%3B%0D%0A%0D%0ABusinessDay%3A%3Aenable(%5BCarbon%3A%3Aclass%5D%2C%20%24settings%5B%27holidays%27%5D)%3B%0D%0A%0D%0Avar_dump(Carbon%3A%3Anow()-%3EisHoliday())%3B%0D%0Avar_dump(Carbon%3A%3Aparse(%272021-01-01%27)-%3EisHoliday())%3B%0D%0A

Would you be able to give a minimum code chunk to reproduce on https://try-carbon.herokuapp.com/ please?

**Comment by kylekatarnls** [comment]
Could you also give me your PHP version running this (replacing `now()->isHoliday()` with `echo PHP_VERSION;` and running the code the same way you got the error).

**Comment by mpoma** [comment]
I made some tests.
echo PHP_VERSION;  7.4.3   No errors

If I delete the config file and use enable with baselist = 'us-national', get the same warning;
Then I upload the project to a server and in artisan tinker get the same warning;
Because I get the library this weekend, I dont have especial code involve, just a simple check isHoliday(), is a big project with Laravel Nova.

**Comment by kylekatarnls** [comment]
Creating a Laravel project from scratch and running `now()->isHoliday()` causes no issues, so I can't figure out without a code chunk able to reproduce the bug. Please try to reduce it to the bare minimum to get the error occur, ideally outside Laravel.

**Comment by mpoma** [comment]
OK, close the issue if you like. When I reproduce the bug, I'll contact you. Thanks for you attention (and your LIB)!!!

**Comment by kylekatarnls** [comment]
Actually errors at those lines are supposed to be muted (to fallback to static closure). So you should also check your error reporting setting. May you have something disabling `@`?

**Comment by mpoma** [comment]
this code
Carbon::macro('foo', static function () { return 'foo'; });
echo Carbon::foo();
work 'OK', without warning

**Comment by kylekatarnls** [comment]
What about the other question? Can you give the content of `$macro` on src/Carbon/Traits/Date.php on line 2413 when it fails?

I tried same with a fresh install of laravel 8.25.0. then requiring `cmixin/business-day`, copy-paste your config/carbon.php file then `now()->isHoliday()` worked just fine.

I can't help much more. I can just advise to try to start from a clean app an try to move pieces by chunk to see when it comes to throw the error so you might be able to produce a minimum code to reproduce, then I can add it to unit tests and fix it.

Thanks.

**Comment by JWhiteSS** [comment]
In my project, I have a shutdown function that will log an error if the return value of `error_get_last()` is an error. This warning was muted, however there is still an error. Is there a way to use this without generating errors (even if they're muted)?

**Comment by kylekatarnls** [comment]
Actually there is not much that can be done from business-day side.

This error is thrown and caught from Carbon side, and it's actually done this way because PHP provides no way to know if a given `closure` is static or not.

Only way would be a very verbose and heavy `set_error_handler` around each call that can throw a PHP error.

If you can use `set_error_handler` in your own application globally to throw `ErrorException` instead of native PHP error, you should no longer have this problem and possibly a better control over real PHP errors occurring.
