### ISSUE TITLE
Holiday detected as wednesday when really is Thursday

### ISSUE THREAD

**Issue by mpoma** [kylekatarnls/business-day#65]
I like to request a pull to update ar-national, but when I put this holiday sust

'guemes-day' => '= 06-17 if Tuesday,Wednesday then previous Monday and if Thursday,Friday then next Monday',
is sustitute with 15 (previus) when the real sust is 22-06-2021 (next)

I dont know if Carbon or your lib.......... sorry if Iḿ heavy::::::::

**Comment by kylekatarnls** [comment]
Actually the parser expected `'guemes-day' => '= 06-17 if Tuesday,Wednesday then previous Monday and Thursday,Friday then next Monday',` (`and` instead of `and if`).

But it's not a big deal to accept optional "if" here. So I will add it to the parser.

**Comment by kylekatarnls** [comment]
Fixed in latest release: 1.12.1
