### ISSUE TITLE
Unknown holiday name in pl

### ISSUE THREAD

**Issue by pchochlinska** [kylekatarnls/business-day#71]
`'easter-p1'` and `'11-11'` returns `Unknown` as name
function: `getHolidayName()`

**Comment by kylekatarnls** [comment]
Names are based on community contributions, if you know the translations please submit a pull-request for the file https://github.com/kylekatarnls/business-day/blob/master/src/Cmixin/HolidayNames/pl.php to add the missing keys.

Thanks.

**Comment by diverpl** [comment]
The translations are correct. Just the identifiers used aren't.

`easter-p1` should be `easter-1` - it's "Drugi dzień Wielkanocy" ("The Second Day of Easter") or "Poniedziałek Wielkanocny" ("Easter Monday")
`11-11` should be `independence-day` - it's "Narodowe Święto Niepodległości"
