### ISSUE TITLE
Programatically get a list of available regions

### ISSUE THREAD

**Issue by samatcd** [kylekatarnls/business-day#80]
It would be really handy if we were able to programatically get a list of available regions, instead of having to read available files from `src/Cmixin/Holidays/`.

E.g., 

```php
Carbon::getHolidayRegions(); // ['ad-07', 'ad-national', 'ae-national', ... ] ...etc
```

**Comment by kylekatarnls** [comment]
Fair enough. I would gladly review a pull-request for this if someone wants to implement it.
