### ISSUE TITLE
Cannot get expression to work properly

### ISSUE THREAD

**Issue by betaSavvy** [kylekatarnls/business-day#84]
Hi,

I am trying to set a holiday that if it falls on a sunday, the following monday will be a holiday.

```php
return [
    'hari-raya-puasa' => '= 1 shawwal if sunday then next monday', 
]
```

But got this error
```
Carbon\Exceptions\InvalidFormatException
DateTime::__construct(): Failed to parse time string (1 shawwal 2020) at position 0 (1): Unexpected character
```

What is the right way to achieve it?

**Comment by kylekatarnls** [comment]
Hello,

As of now, alternative calendars (Hijri/Jewish/Lunar) are not compatible with conditional syntax.

I started a fix, you can try it by requiring:
```json
"require": {
  ...
  "cmixin/business-day": "dev-fix/issue-84-support-alt-calendar-with-conditions as 1.14.0"
}
```

As it involves one more RegExp parsing, it might cost some performance so I still have to find a more optimized way.

**Comment by betaSavvy** [comment]
@kylekatarnls 

Wow that was quick! Just did some test with it and working good so far. Nice work!

Then went on to test another holiday - Hari Raya Haji(aka Eid al-Adha) which falls on the 10th day of the 12th month in the Islamic calendar.

```php
return [
    'hari-raya-haji' => '= 10 dhu al-hijjah if sunday then next monday', 
]
```

I tried from year 2000-2021, the following years gave me error in test cases.

`2004-02-01`, `2007-12-27`, `2008-12-08`, `2009-11-27`, `2011-11-06`, `2016-09-12`, `2019-08-11`

I am referencing this source for the particular holiday I am testing [Singapore Public Holidays](https://www.timeanddate.com/holidays/singapore/hari-raya-haji)

and this for the hijri/gregorian calendar [Islamic/Gregorian Calendar](https://www.islamicfinder.org/islamic-calendar/)

Any idea why this happens?

**Comment by kylekatarnls** [comment]
Can you please add `'= 10 dhu al-hijjah'` in your config and check: `Carbon::getYearHolidays()` for each year and for each day what day of week it is, so I can see if either `10 dhu al-hijjah` (based on Hijri calendar) is the mismatch or if the if-then rule fails. Thanks 🙏

**Comment by betaSavvy** [comment]
- Hari Raya Haji: 16/03/2000 Thursday
- Hari Raya Haji: 06/03/2001 Tuesday
- Hari Raya Haji: 23/02/2002 Saturday
- Hari Raya Haji: 12/02/2003 Wednesday
- **Hari Raya Haji: 02/02/2004 Monday** _// this should be observed, actual is 01/02/2004 Sunday_
- Hari Raya Haji: 21/01/2005 Friday
- Hari Raya Haji: 10/01/2006 Tuesday
- **Unknown: 31/12/2006 Sunday** _// No idea where this came out_
- **Hari Raya Haji: 20/12/2007 Thursday** _// actual should be is 27/12/2007 Thursday_
- **Hari Raya Haji: 09/12/2008 Tuesday** _// actual should be is 08/12/2008 Monday_
- **Hari Raya Haji: 28/11/2009 Saturday** _// actual should be is 27/11/2008 Friday_
- Hari Raya Haji: 17/11/2010 Wednesday
- **Hari Raya Haji: 07/11/2011 Monday** _// this should be observed, actual is 06/11/2011 Thursday_
- Hari Raya Haji: 26/10/2012 Friday
- Hari Raya Haji: 15/10/2013 Tuesday
- Hari Raya Haji: 05/10/2014 Sunday
- Hari Raya Haji (observed): 06/10/2014 Monday
- Hari Raya Haji: 24/09/2015 Thursday
- **Hari Raya Haji: 13/09/2016 Tuesday** _// Actual should be is 12/09/2016 Monday_
- Hari Raya Haji: 02/09/2017 Saturday
- Hari Raya Haji: 22/08/2018 Wednesday
- **Hari Raya Haji: 12/08/2019 Monday** _// this should be observed, actual is 11/08/2019 Thursday_
- Hari Raya Haji: 31/07/2020 Friday
- Hari Raya Haji: 20/07/2021 Tuesday

The above data(2000 - 2021) is based on the following config:

```php
return [
    'hari-raya-haji' => '= 10 dhu al-hijjah',
    'hari-raya-haji-observed' => '= 10 dhu al-hijjah if sunday then next monday',
];
```

Year 2014 works correctly with both holiday and observed holiday.

**Comment by kylekatarnls** [comment]
> Unknown: 31/12/2006 Sunday                // No idea about this, the id is hari-raya-haji-oc-2
About this, it's actually logical, lunisolar year are shorter than gregorian year so once in a while there is 2 of them during the same gregorian year. It sounds that it was skipped in Singapore but in [Morroco](https://www.timeanddate.com/holidays/morocco/2006) there were 2 Eid al-Adha at those dates.

So yet another exception I'm not sure how to handle.

**Comment by kylekatarnls** [comment]
> Hari Raya Haji: 20/12/2007 Thursday       // actual should be is 27/12/2007 Thursday

According to https://time.sg/public-holidays-2007 20th is the correct date.

Also on the website used to compare dates ([Islamic/Gregorian Calendar](https://www.islamicfinder.org/islamic-calendar/)) going to the converter page https://www.islamicfinder.org/islamic-date-converter/

It's written:
> There is a small probability of one day error

![image](https://github.com/user-attachments/assets/79f7badf-8007-4c54-841e-d45efc762f6c)

Also, if I check for algos to convert hijri day to julian day, I find both:
```
(int) ((11 * $year + 3) / 30) + 354 * $year + 30 * $month - (int) (($month - 1) / 2) + $day + 1948440 - 385
```

And the exact same algo but with 386.

Not sure where is lying the error, but it's sounds like a known issue not related to the library.

**Comment by betaSavvy** [comment]
@kylekatarnls  Hi, Its been awhile! Thanks for looking into it. This is a rather complicated situation where maybe different countries decides on the holiday on a different date sometimes.

Source: [https://holidayapi.com/countries/sg-04/2007](https://holidayapi.com/countries/sg-04/2007)

For now my solution is to add it to my custom array if the date is different from the default to suit my project.
