### ISSUE TITLE
Relative logic not working on January 1st

### ISSUE THREAD

**Issue by meveridge** [kylekatarnls/business-day#87]
Relative date logic applied to January 1st does not seem to work for specifying a holiday.

Use Case:
This year, 2021 new years day is on a Saturday. Since `substitute` only applies dates forward, I need to adjust the date backwards. e.g. when January 1st is on a Saturday, I want the previous Friday, December 31st as the holiday/non-business day. 

Reproduction:
- New Year date logic: `= 01-01 if Saturday then last Friday`
- Test Date: 20021-12-31
- Expected result: `isHoliday()` === true and `isBusinessDay()` === false

```
$baseList = 'us-national'; // or region such as 'us-il'

// You can add/remove days (optional):
$additionalHolidays = array(
    'new-year' => '= 01-01 if Saturday then last Friday',
    'test' => '= 12-11 if Saturday then last Friday',
);

BusinessDay::enable('Carbon\Carbon', $baseList, $additionalHolidays);

$date = Carbon::parse('2021-12-31');

var_dump($date->isHoliday()); // false
var_dump($date->isBusinessDay()); // true
```

The same logic works on a date that is not January 1st:
```
$date = Carbon::parse('2021-12-10');
var_dump($date->isHoliday()); // true
var_dump($date->isBusinessDay()); // false
```

Is there a way to configure this use case?

**Comment by kylekatarnls** [comment]
Indeed when checking year 2021, the config generated by 2022 holidays is not loaded, that's what substitute date is not working when source date is not in the same year than the destination date. Solving this could have a significant performance cost.

As a work-around, you can check if the date matches a given holiday of the next year using:
```php
var_dump(in_array(
  Carbon::parse('2021-12-31'),
  Carbon::getYearHolidays(2022),
));
```

**Comment by meveridge** [comment]
Thanks for the response; that makes sense. 

Any ideas on a workaround for `nextBusinessDay()` in regards to this? 

I can do some manual checks in this scenario for `isBusinessDay()` but I could have a scenario that returns `2021-12-31` via `nextBusinessDay().` I suppose I could always do manual checks again... just wondering if you know of a more elegant solution?

Scenario:
- Run `isBusinessDay()` on a date that returns false
- Run `nextBusinessDay()` that returns `2021-12-31`
- Run `isBusinessDay()` again, and if that fails run `nextBusinessDay()` again?

**Comment by meveridge** [comment]
Actually setting my config as:
`new-years-eve' => '= 12-31 on Friday` 
in addition to the default `new-year` holiday seems to cover all my bases. 

Thanks again!!

**Comment by kylekatarnls** [comment]
Thanks, this is a very good work-around. I could mention this in the readme and I will check we don't have holidays that could overflow on a different year in our embedded holiday lists.
